# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=200)),
                ('companion_id', models.IntegerField()),
            ],
        ),
    ]
