# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=512)),
                ('comment_text', models.TextField(default=None, max_length=1000)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
